[build]
builder = "nixpacks"
buildCommand = "npm install --prefix server && npm install --prefix client && npm run build --prefix client"

[deploy]
startCommand = "npm run start --prefix server"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[[services]]
internalPort = 3001
